#!/usr/bin/env bash
#transfers a file from our client to a server
ARGV=("$@")
ARGC=("$#")
if [ $ARGC -lt 3 ] 
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp ${ARGV[1]} -o StrictHostKeyChecking no -i ${ARGV[4]} ${ARGV[3]}@${ARGV[2]}:~/
fi
