#!/usr/bin/env bash
#transfers a file from our client to a server
ARGV=("$@")
ARGC=("$#")
if [ ${ARGV[1]} 0 ] 
        then
                echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp ${ARGV[1]}  ${ARGV[3]}@${ARGV[2]}:${ARGV[4]}
fi
