#!/usr/bin/env bash
#it configures a brand new Ubuntu machine to the requirements
apt-get update
apt-get -y install nginx
service nginx start
echo "Holberton School for the win!" | tee /var/www/html/index.html
service nginx restart
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
