#!/usr/bin/env bash
# process_and_pid_file
i=2
j=0
echo $$ > /var/run/holbertonscript.pid
trap 'rm /var/run/holbertonscript.pid' 3
trap 'rm /var/run/holbertonscript.pid' 15
while [ $j -le "$i" ];do
        echo "To infinity and beyond"
        i="$((i+2))"
        j="$((j+2))"
        sleep 2
        trap 'echo "I hate the kill command"' 15
        trap 'echo "Y U no love me?!"' 2
done