#!/usr/bin/env bash
count=0
end=10
while [ $end -ge $count ]
do
        if [ $count = 9 ];then
                echo "Hi"
        else
                echo "Holberton School"
        fi
        ((count++))
done