#!/usr/bin/env bash
count=1
end=10
while [ $end -ge $count ]
do
        if [ $count -eq 4 ];then
                echo "bad luck"
        fi
        if [ $count -eq 8 ];then
                echo "good luck"
        fi
        if [ $count -ne 8 ] && [ $count -ne 4 ];then
                echo "Holberton Schoolco"
        fi
        ((count++))
done