#!/usr/bin/env bash
# bad_luck_8_is_your_chance
count=1
end=10
while [ $end -ge $count ]
do
        if [ $count -eq 4 ];then
                echo "bad luck"
        elif [ $count -eq 8 ];then
                echo "good luck"
        else
                echo "Holberton School"
        fi
        ((count++))
done