#!/usr/bin/env bash
# superstitious_numbers
count=1
end=20
while [ $end -ge $count ]
do
        if [ $count -eq 4 ];then
                echo "bad luck from China"
        elif [ $count -eq 9 ];then
                echo "bad luck from Japan"
        elif [ $count -eq 17 ];then
                echo "bad luck from Italy"
        else
                echo $count
        fi
        ((count++))
done