#!/usr/bin/env bash
# clock
i=0
j=1
number_1=12
number_2=59
while [ $number_1 -ge $i ];do
        echo "Hour: $i"
        ((i++))
        j=1
        while [ $number_2 -ge $j ];do
                echo "$j"
                ((j++))
        done
done