#!/usr/bin/env bash
# Nginx is running as the nginx user.
sudo useradd nginx
echo -e "nginx\nnginx" | passwd nginx
pkill apache2
apt-get update -y
apt-get -y install nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
